export const bangladeshBanks = [
	{ label: 'Sonali Bank Limited' },
	{ label: 'Janata Bank Limited' },
	{ label: 'Agrani Bank Limited' },
	{ label: 'Rupali Bank Limited' },
	{ label: 'Pubali Bank Limited' },
	{ label: 'Uttara Bank Limited' },
	{ label: 'AB Bank Limited' },
	{ label: 'IFIC Bank Limited' },
	{ label: 'Dutch-Bangla Bank Limited' },
	{ label: 'NCC Bank Limited' },
	{ label: 'Southeast Bank Limited' },
	{ label: 'Prime Bank Limited' },
	{ label: 'The City Bank Limited' },
	{ label: 'One Bank Limited' },
	{ label: 'Eastern Bank Limited' },
	{ label: 'Mutual Trust Bank Limited' },
	{ label: 'Standard Bank Limited' },
	{ label: 'Trust Bank Limited' },
	{ label: 'Jamuna Bank Limited' },
	{ label: 'Shahjalal Islami Bank Limited' },
	{ label: 'Social Islami Bank Limited' },
	{ label: 'Islami Bank Bangladesh Limited' },
	{ label: 'Exim Bank Limited' },
	{ label: 'First Security Islami Bank Limited' },
	{ label: 'Bank Asia Limited' },
	{ label: 'BRAC Bank Limited' },
	{ label: 'Meghna Bank Limited' },
	{ label: 'NRB Bank Limited' },
	{ label: 'South Bangla Agriculture and Commerce Bank Limited' },
	{ label: 'Modhumoti Bank Limited' },
];
